language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/ahn-springboot-webservice.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ahn2-springboot-build
    region: us-east-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ahn2-springboot-build
    key: ahn-springboot-webservice.zip
    bundle_type: zip
    application: ahn-springboot-webservice
    deployment_group: ahn-springboot-webservice-group
    region: us-east-2
    wait-until-deployed: true

# C 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ahn.geeeun@gmail.com